import {
  deepFreezeEvalValue,
  type ContentQualityV3EvalStratum,
  type ContentQualityV3TopicSeed,
} from './evalCorpusTypes.js';

function topicSeed(
  stratum: ContentQualityV3EvalStratum,
  topicSignature: string,
  primaryKeyword: string,
  title: string,
  sourceType: string,
  categoryHint: string,
  rawText: string,
  extra: Readonly<Record<string, unknown>> = {},
): ContentQualityV3TopicSeed {
  return {
    stratum,
    topicSignature,
    primaryKeyword,
    minChars: stratum === 'homefeed' ? 2_200 : 2_500,
    requiredExactLiterals: [title],
    source: {
      ...extra,
      sourceType,
      title,
      categoryHint,
      toneStyle: stratum === 'homefeed' ? 'friendly' : 'professional',
      targetAge: 'all',
      rawText,
    },
  };
}

export const CONTENT_QUALITY_V3_TOPIC_SEEDS: readonly ContentQualityV3TopicSeed[] =
  deepFreezeEvalValue([
    topicSeed(
      'seo',
      'seo:portable-blender-price',
      '휴대용 미니 블렌더 선택',
      '휴대용 미니 블렌더 P1',
      'product_spec',
      'kitchen',
      '공식 설명에는 용량 420ml, USB-C 충전, 분리 세척 가능한 컵이 적혀 있다. 얼음 분쇄 성능과 장기 내구성 비교 자료는 제공되지 않았다.',
      { productSpec: '용량 420ml, USB-C 충전, 분리 세척 컵', productInfo: { name: '휴대용 미니 블렌더 P1', category: '주방' } },
    ),
    topicSeed(
      'seo',
      'seo:repair-center-phone',
      '노트북 수리 접수 방법',
      '해봄 노트북 수리센터',
      'business_facts',
      'repair',
      '센터 안내에는 방문 전 증상과 모델명을 정리하고 데이터 백업 여부를 확인하라고 적혀 있다. 문의 전화번호와 당일 수리 보장은 별도 자료에 없다.',
      { businessInfo: { name: '해봄 노트북 수리센터', region: '대전', serviceArea: 'regional' } },
    ),
    topicSeed(
      'seo',
      'seo:robot-vacuum-reviews',
      '로봇청소기 장애물 회피 비교',
      '로봇청소기 R3 비교 자료',
      'comparison_notes',
      'home_appliance',
      '비교 자료에는 낮은 문턱 통과와 전선 회피 평가가 서로 다른 환경에서 진행됐다고 적혀 있다. 최신 점유율이나 모든 집에서의 성능 우위는 확인되지 않았다.',
      { productInfo: { name: '로봇청소기 R3', category: '생활가전' } },
    ),
    topicSeed(
      'seo',
      'seo:medical-blood-pressure',
      '가정용 혈압계 확인 기준',
      '가정용 혈압계 M4',
      'medical_device_guide',
      'health',
      '의료기기 안내에는 올바른 자세와 같은 시간대 측정이 중요하다고 적혀 있다. 측정값만으로 질환을 진단하거나 치료 효과를 보장할 수 없으며 이상 수치는 의료진 상담이 필요하다.',
      { productInfo: { name: '가정용 혈압계 M4', category: '의료기기' } },
    ),
    topicSeed(
      'seo',
      'seo:legal-lease-contract',
      '주택 임대차 계약 상담',
      '주택 임대차 계약 상담 L5',
      'legal_service_notes',
      'law',
      '법률 상담 안내에는 계약서, 특약, 통지 내역을 준비하라고 적혀 있다. 구체적 권리와 분쟁 결과는 사실관계와 최신 임대차 법령 검토 없이 단정할 수 없다.',
      { businessInfo: { name: '주택 임대차 계약 상담 L5', region: '서울', serviceArea: 'regional' } },
    ),
    topicSeed(
      'seo',
      'seo:financial-planning',
      '개인 재무상담 준비',
      '개인 재무상담 F6',
      'financial_service_notes',
      'finance',
      '금융 상담 준비 자료는 소득, 부채, 비상자금과 투자 기간을 먼저 정리하라고 설명한다. 특정 수익률, 원금 보장, 미래 가격 상승을 약속하는 근거는 없다.',
      { businessInfo: { name: '개인 재무상담 F6', serviceArea: 'nationwide' } },
    ),

    topicSeed(
      'homefeed',
      'homefeed:thermal-tumbler-price',
      '출근용 보온 텀블러',
      '출근용 보온 텀블러 H1',
      'product_notes',
      'lifestyle',
      '제품 자료에는 용량 500ml와 분리형 패킹이 적혀 있다. 가방 안 누수 여부는 뚜껑 체결과 패킹 상태에 따라 달라지며 모든 상황의 보온 지속 시간은 확인되지 않았다.',
      { productSpec: '용량 500ml, 분리형 실리콘 패킹', productInfo: { name: '출근용 보온 텀블러 H1', category: '생활' } },
    ),
    topicSeed(
      'homefeed',
      'homefeed:bicycle-repair-phone',
      '동네 자전거 수리 예약',
      '동네 자전거 수리점 H2',
      'business_notes',
      'local_service',
      '수리점 안내는 자전거 종류와 고장 증상을 먼저 전달하면 점검 범위를 정하기 쉽다고 설명한다. 공식 전화번호와 즉시 수리 가능 여부는 제공 자료에 없다.',
      { businessInfo: { name: '동네 자전거 수리점 H2', region: '부산', serviceArea: 'regional' } },
    ),
    topicSeed(
      'homefeed',
      'homefeed:pet-feeder-reviews',
      '반려동물 자동급식기 비교',
      '반려동물 자동급식기 H3',
      'editorial_comparison',
      'pet',
      '비교 메모에는 사료 크기와 배출 구조에 따라 막힘 체감이 달랐다고 적혀 있다. 사용자 의견은 엇갈리며 최신 판매 순위와 모든 반려동물의 적응 여부는 확인되지 않았다.',
      { productInfo: { name: '반려동물 자동급식기 H3', category: '반려동물' } },
    ),
    topicSeed(
      'homefeed',
      'homefeed:medical-sleep-tracker',
      '수면 건강 기록기',
      '수면 건강 기록기 H4',
      'health_editorial',
      'health',
      '건강 안내는 수면 기록기가 생활 습관을 돌아보는 참고 자료가 될 수 있지만 의료 진단을 대신하지 않는다고 설명한다. 불면 증상이나 치료 효과는 의료진 평가 없이 확정할 수 없다.',
      { productInfo: { name: '수면 건강 기록기 H4', category: '건강기기' } },
    ),
    topicSeed(
      'homefeed',
      'homefeed:legal-traffic-settlement',
      '교통사고 합의 상담',
      '교통사고 합의 상담 H5',
      'legal_editorial',
      'law',
      '법률 안내는 사고 기록, 진료 자료, 보험사 연락 내역을 보존하라고 설명한다. 과실 비율과 합의 결과, 소송 승패는 개별 사실관계 확인 없이 단정할 수 없다.',
      { businessInfo: { name: '교통사고 합의 상담 H5', serviceArea: 'nationwide' } },
    ),
    topicSeed(
      'homefeed',
      'homefeed:financial-beginner-investing',
      '초보 투자상담 체크',
      '초보 투자상담 H6',
      'financial_editorial',
      'finance',
      '금융 교육 자료는 투자 목적, 기간, 손실 감내 범위를 먼저 적으라고 안내한다. 원금과 수익을 보장하거나 특정 상품의 미래 성과를 약속하는 정보는 없다.',
      { businessInfo: { name: '초보 투자상담 H6', serviceArea: 'nationwide' } },
    ),

    topicSeed(
      'affiliate',
      'affiliate:camp-chair-price',
      '접이식 캠핑 의자 선택',
      '접이식 캠핑 의자 A1',
      'product_spec',
      'outdoor',
      '공식 상품 설명에는 알루미늄 프레임, 제품 무게 1.2kg, 허용 하중 100kg, 수납 가방 포함이라고 적혀 있다. 장시간 착석감과 내구성 비교 자료는 없다.',
      { productSpec: '알루미늄 프레임, 무게 1.2kg, 허용 하중 100kg', productInfo: { name: '접이식 캠핑 의자 A1', category: '캠핑' } },
    ),
    topicSeed(
      'affiliate',
      'affiliate:washer-service-phone',
      '세탁기 방문점검 예약',
      '세탁기 방문점검 A2',
      'service_offer',
      'repair',
      '서비스 설명에는 모델명, 설치 환경, 고장 증상을 접수한 뒤 방문 가능 지역을 확인한다고 적혀 있다. 검증된 전화번호와 당일 방문 보장은 자료에 없다.',
      { businessInfo: { name: '세탁기 방문점검 A2', region: '인천', serviceArea: 'regional' } },
    ),
    topicSeed(
      'affiliate',
      'affiliate:cordless-vacuum-reviews',
      '무선청소기 사용 조건 비교',
      '무선청소기 A3',
      'product_comparison',
      'home_appliance',
      '제품 비교 자료에는 바닥 종류와 흡입 단계에 따라 사용 시간이 달라진다고 적혀 있다. 구매자 평가는 엇갈리며 최신 판매량과 절대적인 성능 우위 자료는 없다.',
      { productInfo: { name: '무선청소기 A3', category: '생활가전' } },
    ),
    topicSeed(
      'affiliate',
      'affiliate:medical-blood-pressure',
      '가정용 혈압계 구매 기준',
      '가정용 혈압계 A4',
      'medical_product_spec',
      'health',
      '의료기기 자료는 커프 크기와 측정 자세를 확인하라고 안내한다. 사용자 후기는 사용 편의 의견일 뿐 진단 정확도나 치료 결과를 보장하는 임상 근거가 아니다.',
      { productInfo: { name: '가정용 혈압계 A4', category: '의료기기' } },
    ),
    topicSeed(
      'affiliate',
      'affiliate:legal-dashcam',
      '교통사고 기록용 블랙박스',
      '교통사고 기록용 블랙박스 A5',
      'legal_product_guide',
      'law',
      '상품 안내는 사고 영상 보존과 시간 설정 확인이 중요하다고 설명한다. 영상 하나만으로 법적 과실이나 소송 결과가 확정되는 것은 아니며 최신 법률 검토가 필요하다.',
      { productInfo: { name: '교통사고 기록용 블랙박스 A5', category: '자동차용품' } },
    ),
    topicSeed(
      'affiliate',
      'affiliate:financial-planning-subscription',
      '재무설계 구독 서비스',
      '재무설계 구독 서비스 A6',
      'financial_service_offer',
      'finance',
      '서비스 소개는 예산 기록과 목표 점검 기능을 설명한다. 투자 수익률, 원금 보장, 손실 회피를 약속하는 근거와 검증된 상담 연락처는 제공되지 않았다.',
      { businessInfo: { name: '재무설계 구독 서비스 A6', serviceArea: 'nationwide' } },
    ),

    topicSeed(
      'business',
      'business:dishwasher-dealer-price',
      '소형 식기세척기 상담',
      '맑은주방 식기세척기 B1',
      'business_product_facts',
      'local_business',
      '업체 자료에는 설치 공간과 급배수 위치를 먼저 확인한다고 적혀 있다. 제품 가격과 설치비는 현장 조건에 따라 확인하며 임의 할인율은 제공되지 않았다.',
      { productInfo: { name: '맑은주방 식기세척기 B1', category: '주방가전' }, businessInfo: { name: '맑은주방 식기세척기 B1', region: '광주', serviceArea: 'regional' } },
    ),
    topicSeed(
      'business',
      'business:appliance-repair-phone',
      '가전 수리 상담',
      '한결 가전 수리 B2',
      'business_facts',
      'repair',
      '업체 안내는 제품 모델과 증상 확인 후 방문 범위를 정한다고 설명한다. 공식 문의 전화와 당일 수리, 누적 시공 건수는 현재 자료에 없다.',
      { businessInfo: { name: '한결 가전 수리 B2', region: '대구', serviceArea: 'regional' } },
    ),
    topicSeed(
      'business',
      'business:doorlock-reviews',
      '스마트 도어락 설치 비교',
      '스마트 도어락 설치 B3',
      'business_comparison',
      'security',
      '설치 자료에는 문 두께와 잠금 구조에 따라 호환 여부가 달라진다고 적혀 있다. 고객 의견은 편의성과 소음에서 엇갈리며 지역 1위라는 근거는 없다.',
      { businessInfo: { name: '스마트 도어락 설치 B3', region: '수원', serviceArea: 'regional' } },
    ),
    topicSeed(
      'business',
      'business:medical-rehabilitation-clinic',
      '재활의학과 진료 안내',
      '온담 재활의학과 B4',
      'medical_business_facts',
      'health',
      '의료기관 안내는 증상과 검사 결과에 따라 진료 계획이 달라진다고 설명한다. 특정 치료의 완치, 통증 제거, 부작용 없음은 개별 진료 없이 보장할 수 없다.',
      { businessInfo: { name: '온담 재활의학과 B4', region: '서울', serviceArea: 'regional' } },
    ),
    topicSeed(
      'business',
      'business:legal-consultation',
      '민사분쟁 법률상담',
      '바른길 법률상담 B5',
      'legal_business_facts',
      'law',
      '법률사무소 안내는 계약서와 연락 내역 등 사실 자료를 먼저 검토한다고 설명한다. 위법 여부와 승소 가능성은 구체적 사실관계 및 최신 법령 확인 없이 보장하지 않는다.',
      { businessInfo: { name: '바른길 법률상담 B5', region: '서울', serviceArea: 'nationwide' } },
    ),
    topicSeed(
      'business',
      'business:financial-consultation',
      '가계 재무상담',
      '새봄 재무상담 B6',
      'financial_business_facts',
      'finance',
      '재무상담 안내는 현금 흐름과 부채, 목표 기간을 함께 검토한다고 설명한다. 투자 원금, 목표 수익률, 미래 자산 가격을 보장하거나 임의 연락처를 만들 근거는 없다.',
      { businessInfo: { name: '새봄 재무상담 B6', serviceArea: 'nationwide' } },
    ),

    topicSeed(
      'mate',
      'mate:air-purifier-price',
      '휴대용 공기청정기 선택',
      '휴대용 공기청정기 M1',
      'manufacturer_guide',
      'home_appliance',
      '제조사 안내에는 필터 규격과 권장 사용 공간을 확인하라고 적혀 있다. 모든 장소의 미세먼지 감소 효과와 장기 필터 비용은 같은 조건으로 비교되지 않았다.',
      { productInfo: { name: '휴대용 공기청정기 M1', category: '생활가전' } },
    ),
    topicSeed(
      'mate',
      'mate:auto-repair-phone',
      '자동차 정비 예약 준비',
      '동네 자동차 정비 M2',
      'service_guide',
      'automotive',
      '정비 안내는 차량 연식, 주행 중 증상, 경고등 여부를 접수 전에 정리하라고 설명한다. 공식 전화번호와 즉시 정비 가능 여부는 제공되지 않았다.',
      { businessInfo: { name: '동네 자동차 정비 M2', region: '청주', serviceArea: 'regional' } },
    ),
    topicSeed(
      'mate',
      'mate:smart-scale-reviews',
      '스마트 체중계 지표 해석',
      '스마트 체중계 M3',
      'device_guide',
      'health_device',
      '기기 안내는 측정 시간과 바닥 상태에 따라 값이 달라질 수 있다고 설명한다. 사용자 평가는 앱 편의성에서 엇갈리며 최신 시장 1위 자료는 없다.',
      { productInfo: { name: '스마트 체중계 M3', category: '건강기기' } },
    ),
    topicSeed(
      'mate',
      'mate:medical-medication-counseling',
      '복약 상담 확인 사항',
      '복약 상담 안내 M4',
      'medical_guide',
      'health',
      '의료 안내는 복용 중인 약과 알레르기, 증상을 의료진이나 약사에게 정확히 알리라고 설명한다. 임의 중단이나 치료 효과, 부작용 없음은 보장할 수 없다.',
    ),
    topicSeed(
      'mate',
      'mate:legal-lease-dispute',
      '임대차 분쟁 확인 순서',
      '임대차 분쟁 안내 M5',
      'legal_guide',
      'law',
      '법률 안내는 계약서, 특약, 보증금 지급 기록과 통지 내역을 순서대로 확인하라고 설명한다. 승소나 강제집행 결과는 최신 법령과 사실관계 검토 없이 단정할 수 없다.',
    ),
    topicSeed(
      'mate',
      'mate:financial-retirement-pension',
      '퇴직연금 상담 준비',
      '퇴직연금 상담 M6',
      'financial_guide',
      'finance',
      '금융 안내는 운용 기간, 위험 성향, 수수료와 중도 인출 조건을 확인하라고 설명한다. 특정 수익률과 원금 보장, 미래 시장 성과를 약속하는 자료는 없다.',
      { businessInfo: { name: '퇴직연금 상담 M6', serviceArea: 'nationwide' } },
    ),
  ]);
