import { describe, expect, it } from 'vitest';
import {
  applyHeadingKeywordPatch,
  resolveHeadingKeywordCore,
} from '../contentHeadingKeywordPatch';

describe('resolveHeadingKeywordCore', () => {
  it('removes target particles like "에게" instead of treating them as a hardcoded heading prefix', () => {
    expect(resolveHeadingKeywordCore('조나단에게 악플').core).toBe('조나단');
  });

  it('skips forced heading prefixing for person/social-issue keywords such as 악플', () => {
    const result = resolveHeadingKeywordCore('조나단에게 악플');
    expect(result.shouldPatch).toBe(false);
    expect(result.reason).toContain('person-issue');
  });

  // [2026-07-04 실측 버그] 키워드 "비 오는 날 수건 쉰내" → 첫 토큰 "비"(1글자) 스킵 후
  //   동사 관형형 "오는"이 핵심어로 뽑혀 소제목 2개에 "오는 " 접두가 붙어 발행됨.
  it('동사 관형형(-는) 토큰은 핵심어로 뽑지 않는다 — 명사 토큰 우선 (오는 접두 회귀 잠금)', () => {
    const core = resolveHeadingKeywordCore('비 오는 날 수건 쉰내');
    expect(core.core).not.toBe('오는');
    expect(core.core).toBe('수건');
  });

  it('관형형 아닌 일반 키워드 핵심어 추출은 기존 동작 유지 + 전부 관형형이면 폴백', () => {
    expect(resolveHeadingKeywordCore('제습기 전기세').core).toBe('제습기');
    expect(resolveHeadingKeywordCore('다이어트 식단').core).toBe('다이어트');
    expect(resolveHeadingKeywordCore('오는 가는').core).toBe('오는'); // 폴백(기존 동작)
  });
});

describe('applyHeadingKeywordPatch — 관형형 접두 회귀', () => {
  it('어떤 소제목도 "오는 "으로 시작하지 않는다', () => {
    const headings = [
      { title: '단순 건조 문제 아닌 세균 번식의 결과입니다' },
      { title: '수건 쉰내, 세균과 산패한 피지가 만드는 복합적인 문제입니다' },
    ];
    const result = applyHeadingKeywordPatch(headings, '비 오는 날 수건 쉰내', { maxPatches: 2 });
    expect(result.headings.every((h) => !String(h.title).startsWith('오는 '))).toBe(true);
  });
});

describe('applyHeadingKeywordPatch', () => {
  it('does not inject "조나단에게" into every heading for a person issue article', () => {
    const headings = [
      { title: '월드컵 탈락 후 엉뚱한 이름에 불똥이 튄 상황' },
      { title: '팬들이 헷갈린 진짜 선수 이름' },
      { title: 'SNS 확산과 무분별한 비난의 문제점' },
    ];

    const result = applyHeadingKeywordPatch(headings, '조나단에게 악플');

    expect(result.patchedCount).toBe(0);
    expect(result.headings.map((heading) => heading.title)).toEqual(headings.map((heading) => heading.title));
    expect(result.headings.some((heading) => heading.title.startsWith('조나단에게 '))).toBe(false);
  });

  it('cleans target-particle prefixes already generated by the model', () => {
    const headings = [
      { title: '조나단에게 조나단, 월드컵 탈락 후 엉뚱한 이름에 불똥이 튄 상황' },
      { title: '조나단에게 팬들이 헷갈린 진짜 선수 이름' },
      { title: '조나단에게 SNS 확산과 무분별한 비난의 문제점' },
    ];

    const result = applyHeadingKeywordPatch(headings, '조나단에게 악플');

    expect(result.headings.map((heading) => heading.title)).toEqual([
      '조나단, 월드컵 탈락 후 엉뚱한 이름에 불똥이 튄 상황',
      '팬들이 헷갈린 진짜 선수 이름',
      'SNS 확산과 무분별한 비난의 문제점',
    ]);
  });

  it('limits generic keyword prefix repair so every heading does not become repetitive', () => {
    const headings = [
      { title: '신청 전 확인할 조건' },
      { title: '처리 기간이 늦어지는 이유' },
      { title: '온라인에서 확인하는 방법' },
      { title: '마지막으로 점검할 서류' },
    ];

    const result = applyHeadingKeywordPatch(headings, '지원금 조회', { maxPatches: 2 });

    expect(result.patchedCount).toBe(2);
    expect(result.headings.filter((heading) => heading.title.startsWith('지원금 '))).toHaveLength(2);
  });
});
