import { describe, expect, it } from 'vitest';
import {
  applyHeadingKeywordPatch,
  resolveHeadingKeywordCore,
} from '../contentHeadingKeywordPatch';

describe('resolveHeadingKeywordCore', () => {
  it('removes target particles like "에게" instead of treating them as a hardcoded heading prefix', () => {
    expect(resolveHeadingKeywordCore('조나단에게 악플').core).toBe('조나단');
  });

  it('skips forced heading prefixing for person/social-issue keywords such as 악플', () => {
    const result = resolveHeadingKeywordCore('조나단에게 악플');
    expect(result.shouldPatch).toBe(false);
    expect(result.reason).toContain('person-issue');
  });
});

describe('applyHeadingKeywordPatch', () => {
  it('does not inject "조나단에게" into every heading for a person issue article', () => {
    const headings = [
      { title: '월드컵 탈락 후 엉뚱한 이름에 불똥이 튄 상황' },
      { title: '팬들이 헷갈린 진짜 선수 이름' },
      { title: 'SNS 확산과 무분별한 비난의 문제점' },
    ];

    const result = applyHeadingKeywordPatch(headings, '조나단에게 악플');

    expect(result.patchedCount).toBe(0);
    expect(result.headings.map((heading) => heading.title)).toEqual(headings.map((heading) => heading.title));
    expect(result.headings.some((heading) => heading.title.startsWith('조나단에게 '))).toBe(false);
  });

  it('cleans target-particle prefixes already generated by the model', () => {
    const headings = [
      { title: '조나단에게 조나단, 월드컵 탈락 후 엉뚱한 이름에 불똥이 튄 상황' },
      { title: '조나단에게 팬들이 헷갈린 진짜 선수 이름' },
      { title: '조나단에게 SNS 확산과 무분별한 비난의 문제점' },
    ];

    const result = applyHeadingKeywordPatch(headings, '조나단에게 악플');

    expect(result.headings.map((heading) => heading.title)).toEqual([
      '조나단, 월드컵 탈락 후 엉뚱한 이름에 불똥이 튄 상황',
      '팬들이 헷갈린 진짜 선수 이름',
      'SNS 확산과 무분별한 비난의 문제점',
    ]);
  });

  it('limits generic keyword prefix repair so every heading does not become repetitive', () => {
    const headings = [
      { title: '신청 전 확인할 조건' },
      { title: '처리 기간이 늦어지는 이유' },
      { title: '온라인에서 확인하는 방법' },
      { title: '마지막으로 점검할 서류' },
    ];

    const result = applyHeadingKeywordPatch(headings, '지원금 조회', { maxPatches: 2 });

    expect(result.patchedCount).toBe(2);
    expect(result.headings.filter((heading) => heading.title.startsWith('지원금 '))).toHaveLength(2);
  });
});
