import { describe, expect, it } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '..');

function read(relative: string): string {
  return fs.readFileSync(path.join(ROOT, relative), 'utf-8');
}

describe('full auto image retry state', () => {
  it('clears stale generated images while preserving generated content for image-only retry', () => {
    const utils = read('renderer/utils/fullAutoUtils.ts');

    expect(utils).toContain('clearFullAutoGeneratedImageBatch');
    expect(utils).toContain('stripGeneratedImagesFromContent');
    expect(utils).toContain('beginFullAutoImageRegenerationBatch');
    expect(utils).toContain('isFullAutoImageRunCurrent');
    expect(utils).toContain("invalidateFullAutoImageRun('stop-request')");
    expect(utils).toContain("clearFullAutoGeneratedImageBatch(undefined, 'stop-request')");
  });

  it('starts a fresh image batch before full-auto regeneration and rejects late stale results', () => {
    const publishing = read('renderer/modules/publishingHandlers.ts');

    expect(publishing).toContain('beginFullAutoImageRegenerationBatch?.(structuredContent, imageSource)');
    expect(publishing).toContain('isFullAutoImageRunCurrent?.(fullAutoImageRunId, imageSource)');
    expect(publishing).toContain("clearFullAutoGeneratedImageBatch?.(structuredContent, 'image-error')");

    const cleanupIndex = publishing.indexOf("clearFullAutoGeneratedImageBatch?.(structuredContent, 'image-error')");
    const throwIndex = publishing.indexOf('throw imgErr');
    expect(cleanupIndex).toBeGreaterThan(-1);
    expect(throwIndex).toBeGreaterThan(cleanupIndex);
  });

  it('asks before autosave recovery and discards all current session state when declined', () => {
    const renderer = read('renderer/renderer.ts');

    expect(renderer).toContain('askAutosaveRecoveryChoice');
    expect(renderer).toContain('discard-autosave');
    expect(renderer).toContain('clearAutosavedContent();');
    expect(renderer).toContain('resetAllFields();');
    expect(renderer).toContain("clearFullAutoGeneratedImageBatch?.(null, 'autosave-declined')");
  });
});
