// Tests for writeImageFile — SPEC-IMAGE-MODEL-001 Phase 2 dual-write behavior.
// Uses a real temp directory + in-memory BlobStore injected via _setBlobStoreInstanceForTesting.
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import os from 'os';
import path from 'path';
import fs from 'fs/promises';
import { createHash } from 'crypto';

// ---------------------------------------------------------------------------
// Valid PNG buffer large enough to pass writeImageFile's 1KB minimum size check.
// Generated by sharp at test setup time — 100x100 solid color PNG is well above 1KB.
// ---------------------------------------------------------------------------
let MINIMAL_PNG: Buffer;

async function generateTestPng(): Promise<Buffer> {
  const sharp = (await import('sharp')).default;
  // 200x200 solid color PNG — produces ~1366 bytes, safely above the 1KB minimum guard.
  // 100x100 compresses to ~469 bytes (too small) because PNG handles repeating pixels
  // very efficiently; 200x200 crosses the threshold.
  return sharp({
    create: { width: 200, height: 200, channels: 4, background: { r: 128, g: 128, b: 128, alpha: 1 } },
  }).png().toBuffer();
}

// ---------------------------------------------------------------------------
// In-memory BlobStore implementation for testing.
// ---------------------------------------------------------------------------
type InMemoryBlob = {
  bytes: Uint8Array;
  meta: {
    blobId: string;
    mimeType: string;
    width: number;
    height: number;
    byteSize: number;
    sha256: string;
    createdAt: number;
  };
};

function sha256Hex(bytes: Uint8Array): string {
  return createHash('sha256').update(bytes).digest('hex');
}

function makeInMemoryBlobStore() {
  const store = new Map<string, InMemoryBlob>();
  const shaIndex = new Map<string, string>();
  let idCounter = 0;

  const write = async (bytes: Uint8Array, meta: { mimeType: string; width: number; height: number }) => {
    const hash = sha256Hex(bytes);
    // Dedup: same sha256 → return existing.
    if (shaIndex.has(hash)) {
      const existingId = shaIndex.get(hash)!;
      if (store.has(existingId)) {
        return store.get(existingId)!.meta;
      }
    }
    const blobId = `TEST_BLOB_${++idCounter}`;
    const fullMeta = {
      blobId,
      mimeType: meta.mimeType,
      width: meta.width,
      height: meta.height,
      byteSize: bytes.length,
      sha256: hash,
      createdAt: Date.now(),
    };
    store.set(blobId, { bytes, meta: fullMeta });
    shaIndex.set(hash, blobId);
    return fullMeta;
  };

  const read = async (blobId: string) => {
    const entry = store.get(blobId);
    if (!entry) {
      return { ok: false as const, reason: 'missing' as const, placeholder: 'data:image/png;base64,placeholder' };
    }
    return { ok: true as const, bytes: entry.bytes, meta: entry.meta };
  };

  const has = async (blobId: string) => store.has(blobId);
  const hasMany = async (blobIds: string[]) => Promise.all(blobIds.map(has));
  const materializeTempFile = async (_blobId: string) => null;

  return { write, read, has, hasMany, materializeTempFile, _store: store };
}

// ---------------------------------------------------------------------------
// Setup: inject in-memory blob store and temp dir.
// ---------------------------------------------------------------------------
let tmpDir: string;
let inMemoryStore: ReturnType<typeof makeInMemoryBlobStore>;

beforeEach(async () => {
  tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'test-imageutils-'));
  process.env.TEST_MODE = 'true';
  process.env.GENERATED_IMAGES_DIR = tmpDir;

  // Generate a real PNG that exceeds the 1KB minimum size guard in writeImageFile.
  MINIMAL_PNG = await generateTestPng();

  inMemoryStore = makeInMemoryBlobStore();

  // Inject mock blob store so writeImageFile uses it instead of the Electron singleton.
  const { _setBlobStoreInstanceForTesting } = await import('../main/blobStore/singleton.js');
  _setBlobStoreInstanceForTesting(inMemoryStore as any);
});

afterEach(async () => {
  delete process.env.TEST_MODE;
  delete process.env.GENERATED_IMAGES_DIR;

  // Reset singleton to null so next test gets a fresh instance.
  const { _setBlobStoreInstanceForTesting } = await import('../main/blobStore/singleton.js');
  _setBlobStoreInstanceForTesting(null);

  // Clean up temp dir.
  try {
    await fs.rm(tmpDir, { recursive: true, force: true });
  } catch {
    // ignore cleanup errors
  }
});

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('writeImageFile — SPEC-IMAGE-MODEL-001 Phase 2', () => {
  it('returns legacy filePath and previewDataUrl', async () => {
    const { writeImageFile } = await import('../image/imageUtils.js');
    const result = await writeImageFile(MINIMAL_PNG, 'png', 'test-heading');

    expect(result.filePath).toContain(tmpDir);
    expect(result.previewDataUrl).toMatch(/^data:image\/png;base64,/);
  });

  it('returns all blob fields when blob store write succeeds', async () => {
    const { writeImageFile } = await import('../image/imageUtils.js');
    const result = await writeImageFile(MINIMAL_PNG, 'png', 'test-heading');

    expect(result.blobId).toBeDefined();
    expect(result.mimeType).toBe('image/png');
    expect(result.byteSize).toBeGreaterThan(0);
    expect(result.sha256).toMatch(/^[0-9a-f]{64}$/);
    expect(result.createdAt).toBeGreaterThan(0);
    expect(result.width).toBeGreaterThanOrEqual(0);
    expect(result.height).toBeGreaterThanOrEqual(0);
  });

  it('sha256 in result matches actual buffer sha256', async () => {
    const { writeImageFile } = await import('../image/imageUtils.js');
    const result = await writeImageFile(MINIMAL_PNG, 'png', 'sha256-test');

    // We can't compare to MINIMAL_PNG sha256 directly because sharp may reprocess the buffer.
    // Instead, verify the blobId stored in the in-memory store has the same sha256 as result.
    expect(result.blobId).toBeDefined();
    const blobResult = await inMemoryStore.read(result.blobId!);
    expect(blobResult.ok).toBe(true);
    if (blobResult.ok) {
      expect(blobResult.meta.sha256).toBe(result.sha256);
    }
  });

  it('same buffer written twice returns same blobId (dedup)', async () => {
    const { writeImageFile } = await import('../image/imageUtils.js');
    const result1 = await writeImageFile(MINIMAL_PNG, 'png', 'dedup-1');
    const result2 = await writeImageFile(MINIMAL_PNG, 'png', 'dedup-2');

    // Different headings → different filePaths on disk.
    expect(result1.filePath).not.toBe(result2.filePath);
    // Same bytes → same blobId via sha256 dedup.
    expect(result1.blobId).toBe(result2.blobId);
  });

  it('returns blob fields undefined when blob store fails (non-fatal)', async () => {
    // Inject a failing store.
    const failingStore = {
      write: async () => { throw new Error('simulated blob store failure'); },
      read: async () => ({ ok: false as const, reason: 'missing' as const, placeholder: '' }),
      has: async () => false,
      hasMany: async (ids: string[]) => ids.map(() => false),
      materializeTempFile: async () => null,
    };
    const { _setBlobStoreInstanceForTesting } = await import('../main/blobStore/singleton.js');
    _setBlobStoreInstanceForTesting(failingStore as any);

    const { writeImageFile } = await import('../image/imageUtils.js');
    const result = await writeImageFile(MINIMAL_PNG, 'png', 'fail-test');

    // Legacy fields must be present.
    expect(result.filePath).toContain(tmpDir);
    expect(result.previewDataUrl).toMatch(/^data:image\/png;base64,/);
    // Blob fields must be absent.
    expect(result.blobId).toBeUndefined();
    expect(result.sha256).toBeUndefined();
  });

  it('handles jpeg extension correctly (mimeType = image/jpeg)', async () => {
    // Use a minimal JPEG buffer (valid magic bytes).
    const jpegBuffer = Buffer.alloc(1200); // above MIN_IMAGE_SIZE
    jpegBuffer[0] = 0xFF;
    jpegBuffer[1] = 0xD8;
    jpegBuffer[2] = 0xFF;
    jpegBuffer[3] = 0xE0;

    const { writeImageFile } = await import('../image/imageUtils.js');
    // writeImageFile will try sharp; if it fails, it uses original buffer.
    // We mainly check that mimeType is set correctly.
    let result: Awaited<ReturnType<typeof writeImageFile>> | undefined;
    try {
      result = await writeImageFile(jpegBuffer, 'jpg', 'jpeg-test');
    } catch {
      // sharp may fail on the minimal JPEG — that's OK, skip assertion.
      return;
    }
    if (result?.blobId) {
      expect(result.mimeType).toBe('image/jpeg');
    }
  });
});
