// Integration test: writeImageFile → blobStore.read(result.blobId) → same bytes.
// Verifies SPEC-IMAGE-MODEL-001 Phase 2 acceptance A-5: sha256 100% match.
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import os from 'os';
import path from 'path';
import fs from 'fs/promises';
import { createHash } from 'crypto';
import { createBlobStore } from '../main/blobStore/index.js';
import { _setBlobStoreInstanceForTesting } from '../main/blobStore/singleton.js';

// ---------------------------------------------------------------------------
// Larger PNG buffer generated by sharp — satisfies writeImageFile's 1KB minimum
// guard. Generated once in beforeEach to avoid top-level await in test files.
// ---------------------------------------------------------------------------
let MINIMAL_PNG: Buffer;

async function generateTestPng(): Promise<Buffer> {
  const sharp = (await import('sharp')).default;
  // 200x200 solid color PNG — produces ~1366 bytes, safely above the 1KB minimum guard.
  // 100x100 compresses to ~469 bytes (too small); 200x200 crosses the 1KB threshold.
  return sharp({
    create: { width: 200, height: 200, channels: 4, background: { r: 64, g: 128, b: 192, alpha: 1 } },
  }).png().toBuffer();
}

function sha256Hex(bytes: Uint8Array): string {
  return createHash('sha256').update(bytes).digest('hex');
}

// ---------------------------------------------------------------------------
// In-memory FsBackend for testing.
// ---------------------------------------------------------------------------
function makeInMemoryFsBackend(baseDir: string) {
  const files = new Map<string, Buffer>();
  return {
    baseDir,
    tempDir: os.tmpdir(),

    async ensureDir(_p: string): Promise<void> { /* noop */ },

    async readFile(p: string): Promise<Buffer> {
      const data = files.get(p);
      if (!data) throw Object.assign(new Error(`ENOENT: ${p}`), { code: 'ENOENT' });
      return data;
    },

    async writeFile(p: string, data: Buffer): Promise<void> {
      files.set(p, data);
    },

    async exists(p: string): Promise<boolean> {
      return files.has(p);
    },

    async copyFile(src: string, dest: string): Promise<void> {
      const data = files.get(src);
      if (!data) throw new Error(`ENOENT: ${src}`);
      files.set(dest, data);
    },
  };
}

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------
let tmpDir: string;

beforeEach(async () => {
  tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'test-roundtrip-'));
  process.env.TEST_MODE = 'true';
  process.env.GENERATED_IMAGES_DIR = tmpDir;

  // Generate real PNG — must be above 1KB to pass writeImageFile's size guard.
  MINIMAL_PNG = await generateTestPng();

  // Inject in-memory blob store backed by real createBlobStore but with fake FS.
  const backend = makeInMemoryFsBackend(tmpDir);
  const store = createBlobStore(backend as any);
  _setBlobStoreInstanceForTesting(store as any);
});

afterEach(async () => {
  delete process.env.TEST_MODE;
  delete process.env.GENERATED_IMAGES_DIR;
  _setBlobStoreInstanceForTesting(null);
  try {
    await fs.rm(tmpDir, { recursive: true, force: true });
  } catch {
    // ignore
  }
});

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('image generation roundtrip — SPEC-IMAGE-MODEL-001 A-5', () => {
  it('writeImageFile → blobStore.read → sha256 matches (A-5)', async () => {
    const { writeImageFile } = await import('../image/imageUtils.js');
    const { getBlobStoreInstance } = await import('../main/blobStore/singleton.js');

    const result = await writeImageFile(MINIMAL_PNG, 'png', 'roundtrip-test');

    expect(result.blobId).toBeDefined();
    expect(result.sha256).toBeDefined();

    // Read back from blob store.
    const readResult = await getBlobStoreInstance().read(result.blobId!);
    expect(readResult.ok).toBe(true);

    if (readResult.ok) {
      // Verify sha256 of retrieved bytes matches stored sha256.
      const retrievedHash = sha256Hex(readResult.bytes);
      expect(retrievedHash).toBe(result.sha256);
      expect(retrievedHash).toBe(readResult.meta.sha256);
      // Byte size must match.
      expect(readResult.bytes.length).toBe(result.byteSize);
    }
  });

  it('blobStore.has(blobId) returns true after writeImageFile', async () => {
    const { writeImageFile } = await import('../image/imageUtils.js');
    const { getBlobStoreInstance } = await import('../main/blobStore/singleton.js');

    const result = await writeImageFile(MINIMAL_PNG, 'png', 'has-check');
    expect(result.blobId).toBeDefined();

    const exists = await getBlobStoreInstance().has(result.blobId!);
    expect(exists).toBe(true);
  });

  it('two writeImageFile calls with same buffer yield same blobId', async () => {
    const { writeImageFile } = await import('../image/imageUtils.js');

    const r1 = await writeImageFile(MINIMAL_PNG, 'png', 'dedup-a');
    const r2 = await writeImageFile(MINIMAL_PNG, 'png', 'dedup-b');

    expect(r1.blobId).toBeDefined();
    expect(r2.blobId).toBeDefined();
    expect(r1.blobId).toBe(r2.blobId);
    expect(r1.sha256).toBe(r2.sha256);
  });

  it('result.byteSize matches actual retrieved bytes length', async () => {
    const { writeImageFile } = await import('../image/imageUtils.js');
    const { getBlobStoreInstance } = await import('../main/blobStore/singleton.js');

    const result = await writeImageFile(MINIMAL_PNG, 'png', 'bytesize-check');
    expect(result.blobId).toBeDefined();

    const readResult = await getBlobStoreInstance().read(result.blobId!);
    expect(readResult.ok).toBe(true);
    if (readResult.ok) {
      expect(result.byteSize).toBe(readResult.bytes.length);
    }
  });
});
