import { afterEach, it, expect } from 'vitest';
import { mkdtempSync, readdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';import { join } from 'node:path';
import { PublicationCommitJournal } from '../automation/publicationCommitJournal';
const roots:string[]=[];const setup=()=>{const storageDir=mkdtempSync(join(tmpdir(),'publication-journal-'));roots.push(storageDir);return {storageDir,journal:new PublicationCommitJournal({storageDir})};};afterEach(()=>roots.splice(0).forEach(p=>rmSync(p,{recursive:true,force:true})));
it('restores pending commits after restart without storing raw identities',()=>{const {storageDir,journal}=setup();journal.markSubmitting('private-account','job-secret');expect(new PublicationCommitJournal({storageDir}).hasUnconfirmed('private-account')).toBe(true);expect(journal.hasUnconfirmed('other')).toBe(false);const text=readFileSync(join(storageDir,readdirSync(storageDir)[0]),'utf8');expect(text).not.toContain('private-account');expect(text).not.toContain('job-secret');});
it('rejects duplicate or conflicting submissions and reuses a confirmed result',()=>{const {journal}=setup();journal.markSubmitting('one','first');expect(()=>journal.markSubmitting('one','second')).toThrow();expect(()=>journal.markConfirmed('one','second')).toThrow();journal.markConfirmed('one','first','https://blog.naver.com/example/123');expect(journal.hasUnconfirmed('one')).toBe(false);expect(journal.getConfirmed('one','first')).toEqual({confirmed:true,url:'https://blog.naver.com/example/123'});expect(()=>journal.markSubmitting('one','first')).toThrow();});
it('requires explicit review to permit retry after confirmed nonpublication',()=>{const {journal}=setup();journal.markSubmitting('one','first');journal.confirmOutcome('one','first','not-published');expect(journal.hasUnconfirmed('one')).toBe(false);journal.markSubmitting('one','first');journal.confirmOutcome('one','first','published');expect(journal.getConfirmed('one','first')).toEqual({confirmed:true});});
it('fails closed on damaged journal and storage errors',()=>{const {storageDir,journal}=setup();journal.markSubmitting('one','first');writeFileSync(join(storageDir,readdirSync(storageDir)[0]),'{broken');const restored=new PublicationCommitJournal({storageDir});expect(restored.hasUnconfirmed('one')).toBe(true);expect(()=>restored.markSubmitting('one','first')).toThrow();const blocker=join(storageDir,'file');writeFileSync(blocker,'x');const failed=new PublicationCommitJournal({storageDir:blocker});expect(()=>failed.markSubmitting('one','first')).toThrow();expect(failed.hasUnconfirmed('one')).toBe(true);});
